In [1]:
from flask import Flask, request, jsonify
import numpy as np
from keras.preprocessing.sequence import pad_sequences
import pickle

# Max input length (max number of words) 
max_seq_len = 500

class_names = ['Happy', 'Fear', 'Angry', 'Sad']

model = pickle.load(open('./text_model.pickle', 'rb'))
tokenizer = pickle.load(open('./tokenizer.pickle', 'rb'))

app = Flask(__name__)

@app.route('/getmood', methods=['GET'])
def get_mood():
    input = request.args.get('input')
    message = [input]
    print(message)
    # message = ['I am sad']

    seq = tokenizer.texts_to_sequences(message)
    padded = pad_sequences(seq, maxlen=max_seq_len)
    pred = model.predict(padded)

    print(pred)

    output = class_names[np.argmax(pred)]
    data = {
        'message': message,
        'mood': output
    }
    print(output)
    return jsonify(data)

if __name__ == '__main__':
    app.run()

Using TensorFlow backend.


 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)


['I did a lot of work today']


127.0.0.1 - - [09/Oct/2022 23:04:50] "GET /getmood?input=I%20did%20a%20lot%20of%20work%20today HTTP/1.1" 200 -
127.0.0.1 - - [09/Oct/2022 23:04:50] "GET /getmood?input=I%20did%20a%20lot%20of%20work%20today HTTP/1.1" 200 -
127.0.0.1 - - [09/Oct/2022 23:04:50] "GET /getmood?input=I%20did%20a%20lot%20of%20work%20today HTTP/1.1" 200 -
127.0.0.1 - - [09/Oct/2022 23:04:50] "GET /getmood?input=I%20did%20a%20lot%20of%20work%20today HTTP/1.1" 200 -
127.0.0.1 - - [09/Oct/2022 23:04:50] "GET /getmood?input=I%20did%20a%20lot%20of%20work%20today HTTP/1.1" 200 -
127.0.0.1 - - [09/Oct/2022 23:04:50] "GET /getmood?input=I%20did%20a%20lot%20of%20work%20today HTTP/1.1" 200 -
127.0.0.1 - - [09/Oct/2022 23:04:50] "GET /getmood?input=I%20did%20a%20lot%20of%20work%20today HTTP/1.1" 200 -
127.0.0.1 - - [09/Oct/2022 23:04:50] "GET /getmood?input=I%20did%20a%20lot%20of%20work%20today HTTP/1.1" 200 -


[[0.17697518 0.01333998 0.01799232 0.79169255]]
Sad
['I did a lot of work today']
[[0.17697518 0.01333998 0.01799232 0.79169255]]
Sad
['I did a lot of work today']
[[0.17697518 0.01333998 0.01799232 0.79169255]]
Sad
['I did a lot of work today']
[[0.17697518 0.01333998 0.01799232 0.79169255]]
Sad
['I did a lot of work today']
[[0.17697518 0.01333998 0.01799232 0.79169255]]
Sad
['I did a lot of work today']
[[0.17697518 0.01333998 0.01799232 0.79169255]]
Sad
['I did a lot of work today']
[[0.17697518 0.01333998 0.01799232 0.79169255]]
Sad
['I did a lot of work today']
[[0.17697518 0.01333998 0.01799232 0.79169255]]
Sad


127.0.0.1 - - [09/Oct/2022 23:04:53] "GET /getmood?input=I%20did%20a%20lot%20of%20work%20today HTTP/1.1" 200 -


['I did a lot of work today']
[[0.17697518 0.01333998 0.01799232 0.79169255]]
Sad


127.0.0.1 - - [09/Oct/2022 23:06:32] "GET /getmood?input=I%20did%20a%20lot%20of%20work%20today HTTP/1.1" 200 -


['I did a lot of work today']
[[0.17697518 0.01333998 0.01799232 0.79169255]]
Sad


127.0.0.1 - - [09/Oct/2022 23:06:41] "GET /getmood?input=I%20am%20happy HTTP/1.1" 200 -


['I am happy']
[[9.9003112e-01 3.0302012e-05 7.8446617e-05 9.8601282e-03]]
Happy


127.0.0.1 - - [09/Oct/2022 23:06:49] "GET /getmood?input=i%20am%20sad HTTP/1.1" 200 -


['i am sad']
[[2.4980244e-03 1.3719298e-04 1.6260729e-04 9.9720216e-01]]
Sad
